# # metric to url mapping
# income_statement_dict = ['Unnamed: 0',
#                         'date',
#                         'symbol',
#                         'filing_date',
#                         'accepted_date',
#                         'quarter_year',
#                         'revenue_sales',
#                         'cost_of_sales_cost_of_revenue_cost_of_goods_sold',
#                         'gross_profit_gross_income',
#                         'gross_income_ratio_gross_profit_ratio',
#                         'research_and_development_expenses',
#                         'general_and_administrative_expenses',
#                         'sales_general_and_administrative_expenses',
#                         'other_expenses',
#                         'operating_expenses',
#                         'cost_and_expenses',
#                         'interest_expense',
#                         'depreciation_and_amortization',
#                         'ebitda',
#                         'ebitda_ratio',
#                         'operating_income',
#                         'operating_income_ratio',
#                         'other_income_other_expenses_net',
#                         'income_before_tax_provisions',
#                         'income_before_tax_ratio',
#                         'income_tax_expense_provisions',
#                         'net_income',
#                         'net_income_ratio',
#                         'eps_earnings_per_share',
#                         'eps_earnings_per_share_diluted',
#                         'shares_outstanding',
#                         'shares_outstanding_weighted_diluted',
#                         'sec_filing_url',
#                         'sec_statement_url',]

# balance_sheet_dict = ['Unnamed: 0',
#                     'date',
#                     'symbol',
#                     'filing_date',
#                     'accepted_date',
#                     'period',
#                     'cash_and_cash_equivalents',
#                     'short_term_investments',
#                     'cash_and_short_term_investments',
#                     'net_receivables',
#                     'inventory',
#                     'other_current_assets',
#                     'total_current_assets',
#                     'pp_and_e',
#                     'goodwill',
#                     'intangible_assets',
#                     'goodwill_and_intangible_assets',
#                     'long_term_investments',
#                     'tax_assets',
#                     'other_non_current_assets',
#                     'total_non_current_assets',
#                     'other_assets',
#                     'total_assets',
#                     'accounts_payables',
#                     'short_term_debt',
#                     'tax_payables',
#                     'deferred_revenue',
#                     'other_current_liabilities',
#                     'total_current_liabilities',
#                     'long_term_debt',
#                     'deferred_revenue_non_current',
#                     'deferred_tax_liabilities_non_current',
#                     'other_non_current_liabilities',
#                     'total_non_current_liabilities',
#                     'other_liabilities',
#                     'total_liabilities',
#                     'common_stock',
#                     'retained_earnings',
#                     'accumulated_other_comprehensive_income_loss',
#                     'other_total_stockholders_equity',
#                     'total_stockholders_equity',
#                     'total_liabilities_and_stockholders_equity',
#                     'total_investments',
#                     'total_debt',
#                     'net_debt',
#                     'sec_filing_url',
#                     'sec_statement_url',]

# cash_flow_dict = ['Unnamed: 0',
#                 'date',
#                 'symbol',
#                 'filing_date',
#                 'accepted_date',
#                 'depreciation_and_amortization',
#                 'net_income',
#                 'depreciation_and_amortization',
#                 'deferred_income_tax',
#                 'stock_based_compensation',
#                 'change_in_working_capital',
#                 'accounts_receivable',
#                 'inventory',
#                 'accounts_payables',
#                 'other_working_capital',
#                 'other_non_cash_items',
#                 'net_cash_provided_by_operating_activities',
#                 'investments_in_property_plant_and_equipment',
#                 'acquisitions_net',
#                 'purchases_of_investments',
#                 'sales_maturities_of_investments',
#                 'other_investing_activities',
#                 'net_cash_used_for_investing_activities',
#                 'debt_repayment',
#                 'common_stock_issued',
#                 'common_stock_repurchased',
#                 'dividends_paid',
#                 'other_financing_activities',
#                 'net_cash_used_provided_by_financing_activities',
#                 'effect_of_forex_changes_on_cash',
#                 'net_change_in_cash',
#                 'cash_at_end_of_period',
#                 'cash_at_beginning_of_period',
#                 'operating_cash_flow',
#                 'capital_expenditure',
#                 'free_cash_flow',
#                 'sec_filing_url',
#                 'sec_statement_url',]

fin_statement_raw_names = ['Unnamed: 0',
        'date',
        'symbol',
        'fillingDate',
        'acceptedDate',
        'period',
        'revenue',
        'costOfRevenue',
        'grossProfit',
        'grossProfitRatio',
        'researchAndDevelopmentExpenses',
        'generalAndAdministrativeExpenses',
        'sellingAndMarketingExpenses',
        'otherExpenses',
        'operatingExpenses',
        'costAndExpenses',
        'interestExpense',
        'depreciationAndAmortization_x',
        'ebitda',
        'ebitdaratio',
        'operatingIncome',
        'operatingIncomeRatio',
        'totalOtherIncomeExpensesNet',
        'incomeBeforeTax',
        'incomeBeforeTaxRatio',
        'incomeTaxExpense',
        'netIncome_x',
        'netIncomeRatio',
        'eps',
        'epsdiluted',
        'weightedAverageShsOut',
        'weightedAverageShsOutDil',
        'link',
        'finalLink',
        'cashAndCashEquivalents',
        'shortTermInvestments',
        'cashAndShortTermInvestments',
        'inventory_x',
        'otherCurrentAssets',
        'totalCurrentAssets',
        'propertyPlantEquipmentNet',
        'goodwill',
        'intangibleAssets',
        'goodwillAndIntangibleAssets',
        'longTermInvestments',
        'taxAssets',
        'otherAssets',
        'totalAssets',
        'accountPayables',
        'shortTermDebt',
        'taxPayables',
        'deferredRevenue',
        'otherCurrentLiabilities',
        'totalCurrentLiabilities',
        'longTermDebt',
        'deferredRevenueNonCurrent',
        'deferredTaxLiabilitiesNonCurrent',
        'otherNonCurrentLiabilities',
        'totalNonCurrentLiabilities',
        'otherLiabilities',
        'totalLiabilities',
        'commonStock',
        'retainedEarnings',
        'accumulatedOtherComprehensiveIncomeLoss',
        'othertotalStockholdersEquity',
        'totalStockholdersEquity',
        'totalLiabilitiesAndStockholdersEquity',
        'totalInvestments',
        'totalDebt',
        'netDebt',
        # 'netIncome_y',
        # 'depreciationAndAmortization_y',
        'deferredIncomeTax',
        'stockBasedCompensation',
        'changeInWorkingCapital',
        'accountsReceivables',
        'otherWorkingCapital',
        'otherNonCashItems',
        'netCashProvidedByOperatingActivities',
        'investmentsInPropertyPlantAndEquipment',
        'acquisitionsNet',
        'purchasesOfInvestments',
        'salesMaturitiesOfInvestments',
        'otherInvestingActivites',
        'netCashUsedForInvestingActivites',
        'debtRepayment',
        'commonStockIssued',
        'commonStockRepurchased',
        'dividendsPaid',
        'otherFinancingActivites',
        'netCashUsedProvidedByFinancingActivities',
        'effectOfForexChangesOnCash',
        'netChangeInCash',
        'cashAtEndOfPeriod',
        'cashAtBeginningOfPeriod',
        'operatingCashFlow',
        'capitalExpenditure',
        'freeCashFlow',
        "QQ-YYYY",
        "Year"]
fin_statement_renamed_titles = [

                                'Index',
                                'Date',
                                'Symbol',
                                'Filing Date',
                                'Accepted Date',
                                'Period',
                                'Net Revenue (Sales)',
                                'Cost of Revenue (Sales)',
                                'Gross Profit Margin',
                                'Gross Profit Margin Ratio',
                                'Research and Development (R&D)',
                                'Selling, General, and Administrative (SG&A)',
                                'Selling & Marketing Expenses (S&M)',
                                'Other Income/Expenses, Net',
                                'Total Operating Expenses',
                                'Cost & Expenses',
                                'Interest Expense/Income, Net',
                                'Depreciation & Amortization (D&A)',
                                'EBITDA',
                                'EBITDA Margin',
                                'Operating Income',
                                'Operating Margin',
                                'Total Other Income/Expenses',
                                'Pretax Income (Earnings)',
                                'Pretax Income (Earnings) Margin',
                                'Provision For Income Taxes',
                                'Net Income (Earnings)',
                                'Net Profit Margin',
                                'Earnings Per Share (EPS)',
                                'Earnings Per Share (EPS) Diluted',
                                'Shares Outstanding',
                                'Shares Outstanding (Diluted)',
                                'sec_filing_link',
                                'sec_statement_link',
                                'Cash and Cash Equivalents',
                                'Short Term Investments',
                                'Cash And Short-Term Investments',
                                'Inventory',
                                'Other Current Assets',
                                'Total Current Assets',
                                'PP&E',
                                'Goodwill',
                                'Intangible Assets',
                                'Goodwill and Intangible Assets',
                                'Long-term Investments',
                                'Tax Assets',
                                'Other Assets',
                                'Total Assets',
                                'Accounts Payables',
                                'Short-term Debt',
                                'Income Tax Payables',
                                'Deferred Revenue',
                                'Other Current Liabilities',
                                'Total Current Liabilities',
                                'Long-term Debt',
                                'Deferred Revenue Non-Current',
                                'Deferred Tax Liabilities Non-Current',
                                'Other Non-Current Liabilities',
                                'Total Non-Current Liabilities',
                                'Other Liabilities',
                                'Total Liabilities',
                                'Common Stock',
                                'Retained Earnings',
                                'Accumulated Other Comprehensive Income Loss',
                                'Other Shareholders Equity',
                                'Total Shareholders Equity',
                                'Total Liabilities & Stockholders Equity',
                                'Total Investments',
                                'Total Debt',
                                'Net Debt',
                                'Deferred Income Tax',
                                'Stock-Based Compensation (SBC)',
                                'Change in Working Capital',
                                'Accounts Receivables',
                                'Other Working Capital',
                                'Other Non-Cash Items',
                                'Net Cash Provided by Operating Activities',
                                'Investments in PP&E',
                                'Acquisitions (Net)',
                                'Purchase of Investments',
                                'Sales/Maturities of Investments',
                                'Other Investing Activities',
                                'Net Cash used for Investing Activities',
                                'Debt Repayment',
                                'Common Stock Issued',
                                'Common Stock Repurchased',
                                'Dividends Paid',
                                'Other Financing Activities',
                                'Net Cash Used Provided by Financing Activities',
                                'Effect of Exchange Rate Changes on Cash',
                                'Net Change in Cash',
                                'Cash at End of Period',
                                'Cash at Beginning of Period',
                                'Operating Cash Flow',
                                'Capital Expenditure (capex)',
                                'Free Cash Flow',
                                'QQ-YYYY',
                                'Year',

                                ]
fin_statement_renamed_cols = ['index',
                'date',
                'symbol',
                'filing_date',
                'accepted_date',
                'period',
                'net_revenue',
                'cost_of_sales',
                'gross_profit_margin_non',
                'gross_profit_margin_ratio',
                'r_n_d',
                'g_n_a',
                's_n_m',
                'other_income',
                'total_opex',
                'cost_expenses',
                'interest_expense',
                'd_n_a',
                'ebitda_non',
                'ebitda_margin',
                'operating_income',
                'operating_margin',
                'total_other_income',
                'pretax_income_non',
                'pretax_income_margin',
                'income_tax_expense',
                'net_income',
                'net_profit_margin',
                'eps_non',
                'eps_diluted',
                'shares_outstanding_non',
                'shares_outstanding_diluted',
                'sec_filing_link',
                'sec_statement_link',
                'cash_non',
                'short_term_investments',
                'cash_n_short_term_investments',
                'inventory',
                'other_current_assets',
                'total_current_assets',
                'pp_n_e',
                'goodwill',
                'intangible_assets',
                'goodwill_n_intangible_assets',
                'long_term_investments',
                'tax_assets',
                'other_assets',
                'total_assets',
                'accounts_payable',
                'short_term_debt',
                'income_tax_payables',
                'deferred_revenue',
                'other_current_liabilities',
                'total_current_liabilities',
                'long_term_debt',
                'deferred_revenue_non_current',
                'deferred_tax_liabilities_non_current',
                'other_non_current_liabilities',
                'total_non_current_liabilities',
                'other_liabilities',
                'total_liabilities',
                'common_stock',
                'retained_earnings',
                'accumulated_other_comprehensive_income',
                'other_se',
                'total_se',
                'total_l_se',
                'total_investments',
                'total_debt',
                'net_debt',
                'deferred_income_tax',
                'sbc',
                'change_in_working_capital',
                'accounts_receivable',
                'other_working_capital',
                'other_non_cash_items',
                'net_cash_by_operating_activities',
                'investments_in_pp_n_e',
                'acquisitions_net',
                'purchase_of_investments',
                'sales_maturities_of_investments',
                'other_investing_activities',
                'net_cash_used_for_investing_activities',
                'debt_repayment',
                'common_stock_issued',
                'common_stock_repurchased',
                'dividends_paid',
                'other_financing_activities',
                'net_cash_used_provided_by_financing_activities',
                'effect_of_fx_rate_changes_on_cash',
                'net_change_in_cash',
                'cash_at_end_of_period',
                'cash_at_beginning_of_period',
                'operating_cash_flow',
                'capex',
                'free_cash_flow',
                "QQ-YYYY",
                "Year"]

fin_statement_title_statements_dict = {
                                        "Index": '',
                                        "index": '',
                                        "Date": '',
                                        "Symbol": '',
                                        "Filing Date": '',
                                        "Accepted Date": '',
                                        "Period": '',
                                        "Net Revenue (Sales)": 'income-statement',
                                        "Cost of Revenue (Sales)": 'income-statement',
                                        "Gross Profit Margin": 'income-statement',
                                        "Gross Profit Margin Ratio": 'income-statement',
                                        "Research and Development (R&D)": 'income-statement',
                                        "Selling, General, and Administrative (SG&A)": 'income-statement',
                                        "Selling & Marketing Expenses (S&M)": 'income-statement',
                                        "Other Income/Expenses, Net": 'income-statement',
                                        "Total Operating Expenses": 'income-statement',
                                        "Cost & Expenses": 'income-statement',
                                        "Interest Expense/Income, Net": 'income-statement',
                                        "Depreciation & Amortization (D&A)": 'income-statement',
                                        "EBITDA": 'income-statement',
                                        "EBITDA Margin": 'income-statement',
                                        "Operating Income": 'income-statement',
                                        "Operating Margin": 'income-statement',
                                        "Total Other Income/Expenses": 'income-statement',
                                        "Pretax Income (Earnings)": 'income-statement',
                                        "Pretax Income (Earnings) Margin": 'income-statement',
                                        "Provision For Income Taxes": 'income-statement',
                                        "Net Income (Earnings)": 'income-statement',
                                        "Net Profit Margin": 'income-statement',
                                        "Earnings Per Share (EPS)": 'income-statement',
                                        "Earnings Per Share (EPS) Diluted": 'income-statement',
                                        "Shares Outstanding": 'income-statement',
                                        "Shares Outstanding (Diluted)": 'income-statement',
                                        "sec_filing_link',": 'income-statement',
                                        "sec_statement_link',": 'income-statement',
                                        "Cash and Cash Equivalents": 'balance-sheet',
                                        "Short Term Investments": 'balance-sheet',
                                        "Cash And Short-Term Investments": 'balance-sheet',
                                        "Inventory": 'balance-sheet',
                                        "Other Current Assets": 'balance-sheet',
                                        "Total Current Assets": 'balance-sheet',
                                        "PP&E": 'balance-sheet',
                                        "Goodwill": 'balance-sheet',
                                        "Intangible Assets": 'balance-sheet',
                                        "Goodwill and Intangible Assets": 'balance-sheet',
                                        "Long-term Investments": 'balance-sheet',
                                        "Tax Assets": 'balance-sheet',
                                        "Other Non-Current Assets": 'balance-sheet',
                                        "Total Non-Current Assets": 'balance-sheet',
                                        "Other Assets": 'balance-sheet',
                                        "Total Assets": 'balance-sheet',
                                        "Accounts Payables": 'balance-sheet',
                                        "Short-term Debt": 'balance-sheet',
                                        "Income Tax Payables": 'balance-sheet',
                                        "Deferred Revenue": 'balance-sheet',
                                        "Other Current Liabilities": 'balance-sheet',
                                        "Total Current Liabilities": 'balance-sheet',
                                        "Long-term Debt": 'balance-sheet',
                                        "Deferred Revenue Non-Current": 'balance-sheet',
                                        "Deferred Tax Liabilities Non-Current": 'balance-sheet',
                                        "Other Non-Current Liabilities": 'balance-sheet',
                                        "Total Non-Current Liabilities": 'balance-sheet',
                                        "Other Liabilities": 'balance-sheet',
                                        "Total Liabilities": 'balance-sheet',
                                        "Common Stock": 'balance-sheet',
                                        "Retained Earnings": 'balance-sheet',
                                        "Accumulated Other Comprehensive Income Loss": 'balance-sheet',
                                        "Other Shareholders Equity": 'balance-sheet',
                                        "Total Shareholders Equity": 'balance-sheet',
                                        "Total Liabilities & Stockholders Equity": 'balance-sheet',
                                        "Total Investments": 'balance-sheet',
                                        "Total Debt": 'balance-sheet',
                                        "Net Debt": 'balance-sheet',
                                        "Deferred Income Tax": 'cash-flow-statement',
                                        "Stock-Based Compensation (SBC)": 'cash-flow-statement',
                                        "Change in Working Capital": 'cash-flow-statement',
                                        "Accounts Receivables": 'cash-flow-statement',
                                        "Other Working Capital": 'cash-flow-statement',
                                        "Other Non-Cash Items": 'cash-flow-statement',
                                        "Net Cash Provided by Operating Activities": 'cash-flow-statement',
                                        "Investments in PP&E": 'cash-flow-statement',
                                        "Acquisitions (Net)": 'cash-flow-statement',
                                        "Purchase of Investments": 'cash-flow-statement',
                                        "Sales/Maturities of Investments": 'cash-flow-statement',
                                        "Other Investing Activities": 'cash-flow-statement',
                                        "Net Cash used for Investing Activities": 'cash-flow-statement',
                                        "Debt Repayment": 'cash-flow-statement',
                                        "Common Stock Issued": 'cash-flow-statement',
                                        "Common Stock Repurchased": 'cash-flow-statement',
                                        "Dividends Paid": 'cash-flow-statement',
                                        "Other Financing Activities": 'cash-flow-statement',
                                        "Net Cash Used Provided by Financing Activities": 'cash-flow-statement',
                                        "Effect of Exchange Rate Changes on Cash": 'cash-flow-statement',
                                        "Net Change in Cash": 'cash-flow-statement',
                                        "Cash at End of Period": 'cash-flow-statement',
                                        "Cash at Beginning of Period": 'cash-flow-statement',
                                        "Operating Cash Flow": 'cash-flow-statement',
                                        "Capital Expenditure (capex)": 'cash-flow-statement',
                                        "Free Cash Flow": 'cash-flow-statement',
                                        "QQ-YYYY": '',
                                        "Year": '',
                                        }
fin_statement_title_links_dict ={
                                "index": 'index',
                                "Date": 'date',
                                "Symbol": 'symbol',
                                "Filing Date": 'filing-date',
                                "Accepted Date": 'accepted-date',
                                "Period": 'period',
                                "Net Revenue (Sales)": 'revenue-sales',
                                "Cost of Revenue (Sales)": 'cost-of-sales-cost-of-revenue-cost-of-goods-sold',
                                "Gross Profit Margin": 'gross-profit-gross-income',
                                "Gross Profit Margin Ratio": 'gross-income-ratio-gross-profit-ratio',
                                "Research and Development (R&D)": 'research-and-development-expenses',
                                "Selling, General, and Administrative (SG&A)": 'selling-general-and-administrative-expenses',
                                "Selling & Marketing Expenses (S&M)": 's-and-m-selling-and-marketing-expenses',
                                "Other Income/Expenses, Net": 'other-expenses',
                                "Total Operating Expenses": 'operating-expenses',
                                "Cost & Expenses": 'cost-and-expenses',
                                "Interest Expense/Income, Net": 'interest-expense',
                                "Depreciation & Amortization (D&A)": 'depreciation-and-amortization',
                                "EBITDA": 'ebitda',
                                "EBITDA Margin": 'ebitda-ratio',
                                "Operating Income": 'operating-income',
                                "Operating Margin": 'operating-income-ratio',
                                "Total Other Income/Expenses": 'other-income-other-expenses-net',
                                "Pretax Income (Earnings)": 'income-before-tax-provisions',
                                "Pretax Income (Earnings) Margin": 'income-before-tax-ratio',
                                "Provision For Income Taxes": 'income-tax-expense-provisions',
                                "Net Income (Earnings)": 'net-income',
                                "Net Profit Margin": 'net-income-ratio',
                                "Earnings Per Share (EPS)": 'eps-earnings-per-share',
                                "Earnings Per Share (EPS) Diluted": 'eps-earnings-per-share-diluted',
                                "Shares Outstanding": 'shares-outstanding',
                                "Shares Outstanding (Diluted)": 'shares-outstanding-weighted-diluted',
                                "sec_filing_link',": 'sec_filing_link',
                                "sec_statement_link',": 'sec_statement_link',
                                "Cash and Cash Equivalents": 'cash-and-cash-equivalents',
                                "Short Term Investments": 'short-term-investments',
                                "Cash And Short-Term Investments": 'cash-and-short-term-investments',
                                "Inventory": 'net-receivables',
                                "Other Current Assets": 'inventory',
                                "Total Current Assets": 'total-current-assets',
                                "PP&E": 'pp-and-e',
                                "Goodwill": 'goodwill',
                                "Intangible Assets": 'intangible-assets',
                                "Goodwill and Intangible Assets": 'goodwill-and-intangible-assets',
                                "Long-term Investments": 'long-term-investments',
                                "Tax Assets": 'tax-assets',
                                "Other Non-Current Assets": 'other-non-current-assets',
                                "Total Non-Current Assets": 'total-non-current-assets',
                                "Other Assets": 'other-assets',
                                "Total Assets": 'total-assets',
                                "Accounts Payables": 'accounts-payables',
                                "Short-term Debt": 'short-term-debt',
                                "Income Tax Payables": 'tax-payables',
                                "Deferred Revenue": 'deferred-revenue',
                                "Other Current Liabilities": 'other-current-liabilities',
                                "Total Current Liabilities": 'total-current-liabilities',
                                "Long-term Debt": 'long-term-debt',
                                "Deferred Revenue Non-Current": 'deferred-revenue-non-current',
                                "Deferred Tax Liabilities Non-Current": 'deferred-tax-liabilities-non-current',
                                "Other Non-Current Liabilities": 'other-non-current-liabilities',
                                "Total Non-Current Liabilities": 'total-non-current-liabilities',
                                "Other Liabilities": 'other-liabilities',
                                "Total Liabilities": 'total-liabilities',
                                "Common Stock": 'common-stock',
                                "Retained Earnings": 'retained-earnings',
                                "Accumulated Other Comprehensive Income Loss": 'accumulated-other-comprehensive-income-loss',
                                "Other Shareholders Equity": 'other-total-stockholders-equity',
                                "Total Shareholders Equity": 'total-stockholders-equity',
                                "Total Liabilities & Stockholders Equity": 'total-liabilities-and-stockholders-equity',
                                "Total Investments": 'total-investments',
                                "Total Debt": 'total-debt',
                                "Net Debt": 'net-debt',
                                "Deferred Income Tax": 'deferred-income-tax',
                                "Stock-Based Compensation (SBC)": 'stock-based-compensation',
                                "Change in Working Capital": 'change-in-working-capital',
                                "Accounts Receivables": 'accounts-receivable',
                                "Other Working Capital": 'other-working-capital',
                                "Other Non-Cash Items": 'other-non-cash-items',
                                "Net Cash Provided by Operating Activities": 'net-cash-provided-by-operating-activities',
                                "Investments in PP&E": 'investments-in-property-plant-and-equipment',
                                "Acquisitions (Net)": 'acquisitions-net',
                                "Purchase of Investments": 'purchases-of-investments',
                                "Sales/Maturities of Investments": 'sales-maturities-of-investments',
                                "Other Investing Activities": 'other-investing-activities',
                                "Net Cash used for Investing Activities": 'net-cash-used-for-investing-activities',
                                "Debt Repayment": 'debt-repayment',
                                "Common Stock Issued": 'common-stock-issued',
                                "Common Stock Repurchased": 'common-stock-repurchased',
                                "Dividends Paid": 'dividends-paid',
                                "Other Financing Activities": 'other-financing-activities',
                                "Net Cash Used Provided by Financing Activities": 'net-cash-used-provided-by-financing-activities',
                                "Effect of Exchange Rate Changes on Cash": 'effect-of-forex-changes-on-cash',
                                "Net Change in Cash": 'net-change-in-cash',
                                "Cash at End of Period": 'cash-at-end-of-period',
                                "Cash at Beginning of Period": 'cash-at-beginning-of-period',
                                "Operating Cash Flow": 'operating-cash-flow',
                                "Capital Expenditure (capex)": 'capital-expenditure',
                                "Free Cash Flow": 'free-cash-flow',
                                "QQ-YYYY": 'QQ-YYYY',
                                "Year": 'Year',
                                }
fin_statement_renamed_links = [
                                'index',
                                'date',
                                'symbol',
                                'filing-date',
                                'accepted-date',
                                'period',
                                'revenue-sales',
                                'cost-of-sales-cost-of-revenue-cost-of-goods-sold',
                                'gross-profit-gross-income',
                                'gross-income-ratio-gross-profit-ratio',
                                'research-and-development-expenses',
                                'selling-general-and-administrative-expenses',
                                's-and-m-selling-and-marketing-expenses',
                                'other-expenses',
                                'operating-expenses',
                                'cost-and-expenses',
                                'interest-expense',
                                'depreciation-and-amortization',
                                'ebitda',
                                'ebitda-ratio',
                                'operating-income',
                                'operating-income-ratio',
                                'other-income-other-expenses-net',
                                'income-before-tax-provisions',
                                'income-before-tax-ratio',
                                'income-tax-expense-provisions',
                                'net-income',
                                'net-income-ratio',
                                'eps-earnings-per-share',
                                'eps-earnings-per-share-diluted',
                                'shares-outstanding',
                                'shares-outstanding-weighted-diluted',
                                'sec_filing_link',
                                'sec_statement_link',
                                'cash-and-cash-equivalents',
                                'short-term-investments',
                                'cash-and-short-term-investments',
                                'net-receivables',
                                'inventory',
                                'total-current-assets',
                                'pp-and-e',
                                'goodwill',
                                'intangible-assets',
                                'goodwill-and-intangible-assets',
                                'long-term-investments',
                                'tax-assets',
                                'other-assets',
                                'total-assets',
                                'accounts-payables',
                                'short-term-debt',
                                'tax-payables',
                                'deferred-revenue',
                                'other-current-liabilities',
                                'total-current-liabilities',
                                'long-term-debt',
                                'deferred-revenue-non-current',
                                'deferred-tax-liabilities-non-current',
                                'other-non-current-liabilities',
                                'total-non-current-liabilities',
                                'other-liabilities',
                                'total-liabilities',
                                'common-stock',
                                'retained-earnings',
                                'accumulated-other-comprehensive-income-loss',
                                'other-total-stockholders-equity',
                                'total-stockholders-equity',
                                'total-liabilities-and-stockholders-equity',
                                'total-investments',
                                'total-debt',
                                'net-debt',
                                'deferred-income-tax',
                                'stock-based-compensation',
                                'change-in-working-capital',
                                'accounts-receivable',
                                'other-working-capital',
                                'other-non-cash-items',
                                'net-cash-provided-by-operating-activities',
                                'investments-in-property-plant-and-equipment',
                                'acquisitions-net',
                                'purchases-of-investments',
                                'sales-maturities-of-investments',
                                'other-investing-activities',
                                'net-cash-used-for-investing-activities',
                                'debt-repayment',
                                'common-stock-issued',
                                'common-stock-repurchased',
                                'dividends-paid',
                                'other-financing-activities',
                                'net-cash-used-provided-by-financing-activities',
                                'effect-of-forex-changes-on-cash',
                                'net-change-in-cash',
                                'cash-at-end-of-period',
                                'cash-at-beginning-of-period',
                                'operating-cash-flow',
                                'capital-expenditure',
                                'free-cash-flow',
                                'QQ-YYYY',
                                'Year',


]

metric_to_url_map = {
    'net_working_capital_ratio': "net-working-capital-ratio",
    'book_value_per_share': "book-value-per-share",
    'total_equity_to_total_assets': "total-equity-to-total-assets",
    'operating_cost_ratio': "operating-cost-ratio",
    'percentage_of_debt_to_asset_formula': "perc​entage-of-debt-to-asset-formula",

    'total_liabilities_pct_of_total_assets': "total-liabilities-pct-of-total-assets",
    'debt_to_assets_ratio': "debt-to-assets-ratio",
    'debt_to_equity_ratio': "debt-to-equity-ratio",
    'quick_ratio': "quick-ratio",
    'working_capital': "working-capital",
    'current_ratio': "current-ratio",
    'capital_intensity': "capital-intensity",
    'equity_multiplier': "equity-multiplier",
    'short_term_debt_to_equity_ratio': "short-term-debt-to-equity-ratio",
    'st_debt_as_pct_of_total_debt': "st-debt-as-pct-of-total-debt",
    'acid_test_ratio': "acid-test-ratio",
    'pre_tax_income_to_sales': "pre-tax-income-to-sales",
    'pre_tax_return_on_assets': "pre-tax-return-on-assets",
    'pre_tax_return_on_common_equity': "pre-tax-return-on-common-equity",
    'operating_roa': "operating-roa",
    'operating_profit_margin': "operating-profit-margin",
    'free_operating_cash_flow_to_debt': "free-operating-cash-flow-to-debt",
    'discretionary_cash_flow_to_debt': "discretionary-cash-flow-to-debt",
    'operating_cash_flow_to_interest': "operating-cash-flow-to-interest",
    'operating_cash_flow_to_debt': "operating-cash-flow-to-debt",
    'cash_flow_margin_ratio_formula': "cash-flow-margin-ratio-formula",
    'cash_flow_to_debt': "cash-flow-to-debt",
    'net_cash_flow_to_capital_expenditures': "net-cash-flow-to-capital-expenditures",
    'cash_flow_to_revenue': "cash-flow-to-revenue",
    'cash_return_on_assets': "cash-return-on-assets",
    'cash_return_on_equity': "cash-return-on-equity",
    'cash_to_income_ratio': "cash-to-income-ratio",
    'cash_flow_per_share': "cash-flow-per-share",
    'debt_payment': "debt-payment",
    'debt_coverage': "debt-coverage",
    'cash_flow_from_operations_ratio': "cash-flow-from-operations-ratio",
    'gross_profit_margin': "gross-profit-margin",
    # 'receivables_turnover': "receivables-turnover",
    'capital_turnover_ratio': "capital-turnover-ratio",
    # 'assets_turnover_ratio': "assets-turnover-ratio",
    'accounts_receivable_turnover_ratio': "accounts-receivable-turnover-ratio",
    'operating_cash_flow_to_debt': "operating-cash-flow-to-debt",
    'inventory_ratio': "inventory-ratio",
    'return_on_investment': "return-on-investment",
    'pretax_margin': "pretax-margin",
    'income_to_net_worth_ratio': "income-to-net-worth-ratio",
    'return_on_assets_roa': "return-on-assets-roa",
    'return_on_equity_roe': "return-on-equity-roe",
    'net_profit_margin': "net-profit-margin",
    'earnings_per_share': "earnings-per-share",
    'current_cash_debt_coverage': "current-cash-debt-coverage",
    'cash_debt_coverage': "cash-debt-coverage",
    'long_term_debt_ratio': "long-term-debt-ratio",
    'long_term_debt_equity_ratio': "long-term-debt-equity-ratio",
    'lt_debt_as_pct_of_total_debt': "lt-debt-as-pct-of-total-debt",
    'inventory_pct_of_revenue': "inventory-pct-of-revenue",
    'intangibles_pct_of_book_value': "intangibles-pct-of-book-value",
    'ffo_funds_from_operations_to_debt': "ffo-funds-from-operations-to-debt",
    'operating_margin': "operating-margin",
    'cash_coverage_ratio': "cash-coverage-ratio",
    'ebitda_per_share': "ebitda-per-share",
    'ebitda_interest_coverage': "ebitda-interest-coverage",
    'ebitda_margin': "ebitda-margin",
    'net_margin_profit_margin': "net-margin-profit-margin",
    'return_on_capital_employed_ratio': "return-on-capital-employed-ratio",
    'debt_service_ratio': "debt-service-ratio",
    'return_on_capital': "return-on-capital",
    'dividend_yield': "dividend-yield",
    'dividend_payout_ratio': "dividend-payout-ratio",
    'dividends_per_share': "dividends-per-share",
    'inventory_turnover': "inventory-turnover",
    'cash_ratio': "cash-ratio",
    'cash_flow_roa': "cash-flow-roa",
    'average_collection_period': "average-collection-period",
    'number_of_days_of_receivables': "number-of-days-of-receivables",
    'average_days_payables_outstanding': "average-days-payables-outstanding",
    'days_sales_in_payables': "days-sales-in-payables",
    }

url_to_metric_map = {
    'net-working-capital-ratio': "net_working_capital_ratio",
    'long-term-debt-to-equity-ratio': "long_term_debt_to_equity_ratio",
    # 'roa-cash-flow': "roa_cash_flow",
    'book-value-per-share': "book_value_per_share",
    'total-equity-to-total-assets': "total_equity_to_total_assets",
    'operating-cost-ratio': "operating_cost_ratio",
    'perc​entage-of-debt-to-asset-formula': "perc​entage_of_debt_to_asset_formula",
    'total-liabilities-pct-of-total-assets': "total_liabilities_pct_of_total_assets",
    'debt-to-assets-ratio': "debt_to_assets_ratio",
    'debt-to-equity-ratio': "debt_to_equity_ratio",
    'quick-ratio': "quick_ratio",
    'working-capital': "working_capital",
    'current-ratio': "current_ratio",
    'capital-intensity': "capital_intensity",
    'equity-multiplier': "equity_multiplier",
    'short-term-debt-to-equity-ratio': "short_term_debt_to_equity_ratio",
    'st-debt-as-pct-of-total-debt': "st_debt_as_pct_of_total_debt",
    'acid-test-ratio': "acid_test_ratio",
    'pre-tax-income-to-sales': "pre_tax_income_to_sales",
    'pre-tax-return-on-assets': "pre_tax_return_on_assets",
    'pre-tax-return-on-common-equity': "pre_tax_return_on_common_equity",
    'operating-roa': "operating_roa",
    'operating-profit-margin': "operating_profit_margin",
    'free-operating-cash-flow-to-debt': "free_operating_cash_flow_to_debt",
    'discretionary-cash-flow-to-debt': "discretionary_cash_flow_to_debt",
    'operating-cash-flow-to-interest': "operating_cash_flow_to_interest",
    'operating-cash-flow-to-debt': "operating_cash_flow_to_debt",
    'cash-flow-margin-ratio-formula': "cash_flow_margin_ratio_formula",
    'cash-flow-to-debt': "cash_flow_to_debt",
    'net-cash-flow-to-capital-expenditures': "net_cash_flow_to_capital_expenditures",
    'cash-flow-to-revenue': "cash_flow_to_revenue",
    'cash-return-on-assets': "cash_return_on_assets",
    'cash-return-on-equity': "cash_return_on_equity",
    'cash-to-income-ratio': "cash_to_income_ratio",
    'cash-flow-per-share': "cash_flow_per_share",
    'debt-payment': "debt_payment",
    'debt-coverage': "debt_coverage",
    'cash-flow-from-operations-ratio': "cash_flow_from_operations_ratio",
    'gross-profit-margin': "gross_profit_margin",
    'rece​ivables-turnover': "rece​ivables_turnover",
    'capital-turnover-ratio': "capital_turnover_ratio",
    # 'assets-turnover-ratio': "assets_turnover_ratio",
    'accounts-receivable-turnover-ratio': "accounts_receivable_turnover_ratio",
    'operating-cash-flow-to-debt': "operating_cash_flow_to_debt",
    'inventory-ratio': "inventory_ratio",
    'return-on-investment': "return_on_investment",
    'pretax-margin': "pretax_margin",
    'income-to-net-worth-ratio': "income_to_net_worth_ratio",
    'return-on-assets-roa': "return_on_assets_roa",
    'return-on-equity-roe': "return_on_equity_roe",
    'net-profit-margin': "net_profit_margin",
    'earnings-per-share': "earnings_per_share",
    'current-cash-debt-coverage': "current_cash_debt_coverage",
    'cash-debt-coverage': "cash_debt_coverage",
    'long-term-debt-ratio': "long_term_debt_ratio",
    'long-term-debt-equity-ratio': "long_term_debt_equity_ratio",
    'lt-debt-as-pct-of-total-debt': "lt_debt_as_pct_of_total_debt",
    'inventory-pct-of-revenue': "inventory_pct_of_revenue",
    'intangibles-pct-of-book-value': "intangibles_pct_of_book_value",
    'ffo-funds-from-operations-to-debt': "ffo_funds_from_operations_to_debt",
    'operating-margin': "operating_margin",
    'cash-coverage-ratio': "cash_coverage_ratio",
    'ebitda-per-share': "ebitda_per_share",
    'ebitda-interest-coverage': "ebitda_interest_coverage",
    'ebitda-margin': "ebitda_margin",
    'net-margin-profit-margin': "net_margin_profit_margin",
    'return-on-capital-employed-ratio': "return_on_capital_employed_ratio",
    'debt-service-ratio': "debt_service_ratio",
    'return-on-capital': "return_on_capital",
    'dividend-yield': "dividend_yield",
    'dividend-payout-ratio': "dividend_payout_ratio",
    'dividends-per-share': "dividends_per_share",
    'inventory-turnover': "inventory_turnover",
    'cash-ratio': "cash_ratio",
    'cash-flow-roa': "cash_flow_roa",
    'average-collection-period': "average_collection_period",
    'number-of-days-of-receivables': "number_of_days_of_receivables",
    'average-days-payables-outstanding': "average_days_payables_outstanding",
    'days-sales-in-payables': "days_sales_in_payables",
    }

url_to_definition_map = {
    'current-cash-debt-coverage': "Measures a company's ability to pay off its current liabilities in a given year from its operations",
    'return-on-assets-roa': "In financial analysis, it is the measure of the return on investment. ROA is used in evaluating management's efficiency in using assets to generate income.",
    'inventory-turnover': "Measures liquidity of inventory",
    'net-working-capital-ratio': "",
    'pct-debt-to-asset-formula': "",
    'inventory-ratio': "",
    'rece​ivables-turnover': "",
    'average-collection-period': "",
    'cash-flow-margin-ratio-formula': "",
    'roa-cash-flow': "",
    'cash-ratio': "Measures the ability of a company to pay its current liabilities using cash and marketable securities. Marketable securities are short-term debt instruments that are as good as cash.",
    'cash-debt-coverage': "Measures company's ability to repay its total in a given year from its operations",
    'book-value-per-share': "Measures the amount each share would receive if the company were liquidated at the amount reported on the balance sheet",
    'number-of-days-of-receivables': "",
    'pretax-margin': "",
    'operating-roa': "",
    'operating-cost-ratio': "",
    'operating-profit-margin': "",
    'return-on-capital-employed-ratio': "",
    'dividend-payout-ratio': "",
    'income-to-net-worth-ratio': "",
    'capital-turnover-ratio': "",
    'debt-service-ratio': "",
    'quick-ratio': "",
    'debt-to-assets-ratio': "Debt is defined as the sum of interest-bearing short-term and long-term debt.",
    'debt-to-equity-ratio': "This ratio measures your company's leverage by comparing your liabilities, or debts, to your value as represented by your stockholders' equity.",
    'long-term-debt-ratio': "Similar to the total debt ratio, this formula lets you see your assets available because of debt for longer than a one-year period.",
    # 'assets-turnover-ratio': "You can use this ratio to evaluate how quickly your company is able to collect funds from its customers.",
    'accounts-receivable-turnover-ratio': "You can use this ratio to evaluate how quickly your company is able to collect funds from its customers.",
    'cash-flow-to-debt': "",
    'net-cash-flow-to-capital-expenditures': "",
    'ffo-funds-from-operations-to-debt': "",
    'free-operating-cash-flow-to-debt': "",
    'discretionary-cash-flow-to-debt': "",
    'return-on-capital': "",
    'ebitda-per-share': "",
    'dividends-per-share': "",
    'ebitda-interest-coverage': "",
    'cash-flow-to-revenue': "Operating cash generated per dollar of revenue",
    'cash-return-on-assets': "Operating cash generated per dollar of asset investment",
    'cash-return-on-equity': "Operating cash generated per dollar of owner investment",
    'cash-to-income-ratio': "Cash generated from operations",
    'cash-flow-per-share': "Operating cash flow on a per share basis",
    'debt-payment': "Ability to pay debts with operating cash flows",
    'debt-coverage': "Financial risk and financial leverage",
    'return-on-investment': "",
    'return-on-equity-roe': "",
    'gross-profit-margin': "",
    'pre-tax-income-to-sales': "",
    'pre-tax-return-on-assets': "",
    'pre-tax-return-on-common-equity': "",
    'net-profit-margin': "",
    'earnings-per-share': "",
    'accounts-receivable-turnover': "",
    'days-sales-in-payables': "",
    'capital-intensity': "",
    'working-capital': "",
    'total-equity-to-total-assets': "",
    'equity-multiplier': "Measures the percentage of total assets provided by creditors",
    'cash-coverage-ratio': "",
    'average-days-payables-outstanding': "Liquidity of inventory",
    'operating-margin': "Measures profitability independently of an enterprise's financing and tax positions",
    'dividend-yield': "Percentage of share price distributed as cash dividends",
    'operating-cash-flow-to-interest': "Ability to meet interest payments from operating cash flow. Some analysts calculate the numerator using CFO + interest expense + tax expense. This calculation is less internally consistent as what we are striving for in the numerator is a cash flow number, not a mix of cash flow and accruals.",
    'operating-cash-flow-to-debt': "Ability to repay total liabilities in a given year from operations.",
    'cash-flow-from-operations-ratio': "",
    'ebitda-margin': "",
    'net-margin-profit-margin': "",
    'operating-cash-flow-to-debt': "",
    'current-ratio': "",
    'long-term-debt-to-equity-ratio': "",
    'short-term-debt-to-equity-ratio': "",
    'intangibles-pct-of-book-value': "",
    'inventory-pct-of-revenue': "",
    'lt-debt-as-pct-of-total-debt': "",
    'st-debt-as-pct-of-total-debt': "",
    'total-liabilities-pct-of-total-assets': "",
    'acid-test-ratio': "Also known as 'quick ratio', it measures the ability of a company to pay short-term obligations using the more liquid types of current assets or 'quick assets' (cash, marketable securities, and current receivables).",
}
url_to_equation_map = {
'current-cash-debt-coverage': "Current cash debt coverage = Net cash provided by operating/activities/Average current liabilities",
'return-on-assets-roa': "Return on Assets  = Net Income ÷ Average Total Assets",
'inventory-turnover': "Inventory turnover = Cost of goods sold/Average inventory",
'net-working-capital-ratio': "Net Working Capital = Net Working Capital / Total Assets",
'pct-debt-to-asset-formula': "Percentage of Debt to Asset Formula = Long Term Liabil​ities ⁄ Total Assets x 100%",
'inventory-ratio': "Days' Sales in Invent​ory = 365 days / Inventory Turnover",
'rece​ivables-turnover': "Receivables Turnover = Sales / Accounts Receivable",
'average-collection-period': "Days' Sales in Receivables = 365 days / Receiv​ables Turnover",
'cash-flow-margin-ratio-formula': "Cash Flow Margin Ratio Formula = Actual Cash Flow from Operations ⁄ Revenues from Sales",
'roa-cash-flow': "Cash flow ROA Ratio Formula = Actual Cash Flow from Operations ⁄ Average Total Assets",
'cash-ratio': "Cash Ratio  = (Cash + Marketable Securities ) ÷ Current Liabilities",
'cash-debt-coverage': "Cash debt coverage = Net cash provided by operating activities/Average total liabilities",
'book-value-per-share': "Book value per share = Common stockholding equality/Outstanding shares",
'number-of-days-of-receivables': "Number of days of receivables = (Accounts receivable)/(Average days sales on credit Sales on credit / 365)",
'pretax-margin': "Pretax margin = (EBT (Earnings Before Taxes))/(Revenue)",
'operating-roa': "Operating ROA = (Operating income)/(Average total assets)",
'operating-cost-ratio': "Operating Cost Ratio = Operating Cost/Net Sales X 100",
'operating-profit-margin': "Operating Profit ratio = Operating Profit/Net Sales X 100",
'return-on-capital-employed-ratio': "Return on Capital Employed Ratio = Net Profit after Taxes/ Gross Capital Employed X 100",
'dividend-payout-ratio': "Dividend Pay Out Ratio = Dividend Per Equity Share/Earning Per Equity Share X 100",
'income-to-net-worth-ratio': "Net Profit to Net Worth Ratio = Net Profit after Taxes / Shareholders Net Worth X 100",
'capital-turnover-ratio': "Capital Turnover Ratio = Cost of Sales / Capital Employed",
'debt-service-ratio': "Debt Service Ratio = Net profit Before Interest & Taxes / Fixed Interest Charges",
'quick-ratio': "Quick Ratio = Liquid Assets/Current Liabilities",
'debt-to-assets-ratio': "Debt-to-assets ratio = (Total debt)/(Total assets)",
'debt-to-equity-ratio': "Debt-to-Equity Ratio  = Total Debt/Total Equity",
'long-term-debt-ratio': "Long-Term Debt Ratio  = Long-Term Debt/(Long-Term Debt + Total Equity)",
# 'assets-turnover-ratio': "Accounts Receivable Turnover Ratio  = Sales/Average Accounts Receivable",
'accounts-receivable-turnover-ratio': "Accounts Receivable Turnover Ratio  = Sales/Average Accounts Receivable",
'cash-flow-to-debt': "Discretionary cash flow-to-debt = (CFO - Capital expenditures - Dividend paid)/(Total debt)",
'net-cash-flow-to-capital-expenditures': "Net cash flow-to-capital expenditures = (FFO - Dividends)/(Capital expenditures)",
'ffo-funds-from-operations-to-debt': "FFO (Funds from operations) to debt = (FFO)/(Total debt)",
'free-operating-cash-flow-to-debt': "Free operating cash flow-to-debt = (CFO (adjusted) - Capital expenditures)/(Total debt)",
'discretionary-cash-flow-to-debt': "Discretionary cash flow-to-debt = (FFO + Interest paid - Operatinf lease adjustments)/(Gross interest (prior to deductions for capitalized)/(interest or interest income))",
'return-on-capital': "Return on capital = (EBIT)/(Average capital)",
'ebitda-per-share': "EBITDA per share = (ebitda_is)/(Average number of common stock)",
'dividends-per-share': "Dividends per share = (Dividends paid)/(Number of shares outstanding)",
'ebitda-interest-coverage': "ebitda_is interest coverage = ebitda_is/(Gross interest (prior to deductions for capitalized interest or interest income))",
'cash-flow-to-revenue': "Cash flow to revenue = (CFO)/(Net revenue)",
'cash-return-on-assets': "Cash return on assets = (CFO)/(Average total assets)",
'cash-return-on-equity': "Cash return on equity = (CFO)/(Average shareholders' equity)",
'cash-to-income-ratio': "Cash to income = (CFO)/(Operating income)",
'cash-flow-per-share': "Cash flow per share = (CFO - Pref.dividends)/(Number of common shares outstanding)",
'debt-payment': "Debt payment = (CFO)/(Cash paid for long term debt repayment)",
'debt-coverage': "Debt Coverage = (CFO)/(Total debt)",
'return-on-investment': "Return on investment = Net Income + Interest X (1 - tax rate) / (Equity + long-term debt)",
'return-on-equity-roe': "Return on owner's equity = Net income /Average Owner's Equity",
'gross-profit-margin': "Gross profit margin = Gross Profit / Net Sales or Revenues",
'pre-tax-income-to-sales': "Pre-tax Income to Sales = Pretax income / Net sales",
'pre-tax-return-on-assets': "Pre-tax return on assets = Pretax income / Total assets",
'pre-tax-return-on-common-equity': "Pre-tax return on common equity = Pre-tax / Common equity",
'net-profit-margin': "Net Profit Margin  = Net Income/Sales: The profit margin is an easy way to tell how much of your income comes from sales.",
'earnings-per-share': "Earnings Per Share  = Net Income/Number of Common Shares Outstanding: The earnings-per-share ratio is similar to the return-on-equity ratio, except that this ratio indicates your profitability from the outstanding shares at the end of a given period.",
# 'assets-turnover': "Assets turnover = Net Sales / Average Accounts Receivable",
'accounts-receivable-turnover': "Accounts Receivables turnover = Net Sales / Average Accounts Receivable",
'days-sales-in-payables': "Days sales in payables = Average Accounts and Expenses Payable/(Operating expenses / 365)",
'capital-intensity': "Capital intensity = Average Total assets /Net Sales",
'working-capital': "Working capital = Total Current Assets - Total Current Liabilities",
'total-equity-to-total-assets': "Total equity to total assets = Total equity / Total assets",
'equity-multiplier': "Equity Multiplier = Total Assets / Total Equity",
'cash-coverage-ratio': "Cash coverage = Operating income* + depreciation + amortization / Interest",
'average-days-payables-outstanding': "Inventory turnover = (Cost of goods sold (COGS))/(Average total inventory)",
'operating-margin': "Operating Margin = (EBIT)/(Net sales)",
'dividend-yield': "Dividend Yield = (Cash dividends paid per share of common equity)/(Price per share)",
'operating-cash-flow-to-interest': "CFO to interest = (CFO + interest and taxes paid in cash)/(Interest expense)",
'operating-cash-flow-to-debt': "CFO to debt = (CFO + interest and taxes paid in cash)/(Average total liabilities)",
'cash-flow-from-operations-ratio': "Cash flow from operations ratio = Cash Flow from Operations / Current Liability",
'ebitda-margin': "ebitda_is_margin_is = Earnings before interest, tax, depreciation and amortization / net sales",
'net-margin-profit-margin': "Net Margin (Profit Margin) = net income / sales",
'operating-cash-flow-to-debt': "CFO to debt = Cash flow from operations / total debt",
'current-ratio': "Current Ratio = Current Assets / Current Liabilities",
'long-term-debt-to-equity-ratio': "Long Term Debt/Equity Ratio = Long Term Debt / Shareholders Equity",
'short-term-debt-to-equity-ratio': "Short Term Debt/Equity Ratio = Short Term Debt / Shareholders Equity",
'intangibles-pct-of-book-value': "Intangibles % of Book Value = Intangibles / Shareholders Equity",
'inventory-pct-of-revenue': "Inventory % of Revenue = Inventory / Revenue",
'lt-debt-as-pct-of-total-debt': "LT-Debt as % of Total Debt = Long Term Debt / Total Liabilities",
'st-debt-as-pct-of-total-debt': "ST-Debt as % of Total Debt = Short Term Debt / Total Liabilities",
'total-liabilities-pct-of-total-assets': "Total Liabilities % of Total Assets = Total Liabilities / Total Assets",
'acid-test-ratio': "Acid Test Ratio = Quick Assets ÷ Current Liabilities",
}
url_to_name_map = {
'working-capital': "Working Capital",
'current-ratio': "Current Ratio",
'short-term-debt-to-equity-ratio': "Short Term Debt To Equity Ratio",
'operating-cash-flow-to-interest': "Operating Cash Flow To Interest",
'operating-cash-flow-to-debt': "Operating Cash Flow To Debt",

'current-cash-debt-coverage': "Current Cash Debt Coverage",
'long-term-debt-to-equity-ratio': "Long Term Debt To Equity Ratio",
'ebitda-interest-coverage': "Ebitda Interest Coverage",
'dividend-yield': "Dividend Yield",
'cash-ratio': "Cash Ratio",
'quick-ratio': "Quick Ratio",
'acid-test-ratio': "Acid Test Ratio",
'net-working-capital-ratio': "Net Working Capital Ratio",
'pct-debt-to-asset-formula': "% Debt To Asset Formula",
'rece​ivables-turnover': "Rece​Ivables Turnover",
'inventory-ratio': "Inventory Ratio",
'inventory-turnover': "Inventory Turnover",
'average-collection-period': "Average Collection Period",
'average-days-payables-outstanding': "Average Days Payables Outstanding",
'intangibles-pct-of-book-value': "Intangibles % Of Book Value",
'capital-intensity': "Capital Intensity",
'accounts-receivable-turnover-ratio': "Accounts Receivables Turnover",
'days-sales-in-payables': "Days Sales In Payables",
'number-of-days-of-receivables': "Number Of Days Of Receivables",
# 'assets-turnover-ratio': "Assets Turnover Ratio",
'capital-turnover-ratio': "Capital Turnover Ratio",
'book-value-per-share': "Book Value Per Share",
'cash-debt-coverage': "Cash Debt Coverage",
'total-liabilities-pct-of-total-assets': "Total Liabilities % Of Total_Assets",
'st-debt-as-pct-of-total-debt': "St-Debt As % Of Total Debt",
'lt-debt-as-pct-of-total-debt': "Lt-Debt As % Of Total Debt",
'debt-service-ratio': "Debt Service Ratio",
'total-equity-to-total-assets': "Total Equity To Total_Assets",
'equity-multiplier': "Equity Multiplier",
'cash-coverage-ratio': "Cash Coverage Ratio",
'operating-cash-flow-to-debt': "Operating Cash Flow To Debt",
'debt-to-assets-ratio': "Debt-To-Assets Ratio",
'debt-to-equity-ratio': "Debt-To-Equity Ratio",
'long-term-debt-ratio': "Long-Term Debt Ratio ",
'cash-flow-from-operations-ratio': "Cash Flow From Operations Ratio",
'inventory-pct-of-revenue': "Inventory % Of Revenue",
'cash-flow-margin-ratio-formula': "Cash Flow Margin Ratio Formula",
'roa-cash-flow': "ROA Cash Flow",
'return-on-investment': "Return On Investment",
'return-on-equity-roe': "Return on Equity (ROE)",
'cash-flow-to-revenue': "Cash Flow To Revenue",
'cash-return-on-assets': "Cash Return On Assets",
'cash-return-on-equity': "Cash Return On Equity",
'cash-to-income-ratio': "Cash To Income Ratio",
'cash-flow-per-share': "Cash Flow Per Share",
'debt-payment': "Debt Payment",
'debt-coverage': "Debt Coverage",
'free-operating-cash-flow-to-debt': "Free Operating Cash Flow-To-Debt",
'discretionary-cash-flow-to-debt': "Discretionary Cash Flow-To-Debt",
'cash-flow-to-debt': "Cash Flow-To-Debt",
'net-cash-flow-to-capital-expenditures': "Net Cash Flow-To-Capital Expenditures",
'ffo-funds-from-operations-to-debt': "FFO (Funds From Operations) To Debt",
'ebitda-per-share': "Ebitda Per Share",
'return-on-capital': "Return On Capital",
'dividends-per-share': "Dividends Per Share",
'operating-cost-ratio': "Operating Cost Ratio",
'operating-profit-margin': "Operating Profit Margin",
'income-to-net-worth-ratio': "Income To Net Worth Ratio",
'return-on-capital-employed-ratio': "Return On Capital Employed Ratio",
'dividend-payout-ratio': "Dividend Payout Ratio",
'pre-tax-income-to-sales': "Pre-Tax Income To Sales",
'pre-tax-return-on-assets': "Pre-Tax Return On Assets",
'pre-tax-return-on-common-equity': "Pre-Tax Return On Common Equity",
'gross-profit-margin': "Gross Profit Margin",
'net-profit-margin': "Net Profit Margin",
'earnings-per-share': "Earnings Per Share ",
'operating-margin': "Operating Margin",
'ebitda-margin': "Ebitda Margin",
'net-margin-profit-margin': "Net Margin (Profit Margin)",
'operating-roa': "Operating Roa",
'pretax-margin': "Pretax Margin",
'return-on-assets-roa': "Return On Assets (ROA)",

}
# url_to_name_map = {
                    # 'net-working-capital-ratio': "Net Working Capital Ratio",
                    # 'book-value-per-share': "Book value per share",
                    # 'total-equity-to-total-assets': "Total equity to total_assets",
                    # 'operating-cost-ratio': "Operating Cost Ratio",
                    # 'perc​entage-of-debt-to-asset-formula': "Perc​entage of Debt to Asset Formula",

                    # 'total-liabilities-pct-of-total-assets': "Total Liabilities % of total_assets",
                    # 'debt-to-assets-ratio': "Debt-to-assets ratio",
                    # 'debt-to-equity-ratio': "Debt-to-Equity Ratio",
                    # 'quick-ratio': "Quick Ratio",
                    # 'working-capital': "Working capital",
                    # 'current-ratio': "Current Ratio",
                    # 'capital-intensity': "Capital intensity",
                    # 'equity-multiplier': "Equity Multiplier",
                    # 'short-term-debt-to-equity-ratio': "Short Term Debt to Equity Ratio",
                    # 'st-debt-as-pct-of-total-debt': "ST-Debt as % of Total Debt",
                    # 'acid-test-ratio': "Acid Test Ratio",
                    # 'pre-tax-income-to-sales': "Pre-tax Income to Sales",
                    # 'pre-tax-return-on-assets': "Pre-tax return on assets",
                    # 'pre-tax-return-on-common-equity': "Pre-tax return on common equity",
                    # 'operating-roa': "Operating ROA",
                    # 'operating-profit-margin': "Operating Profit margin",
                    # 'free-operating-cash-flow-to-debt': "Free operating cash flow-to-debt",
                    # 'discretionary-cash-flow-to-debt': "Discretionary cash flow-to-debt",
                    # 'operating-cash-flow-to-interest': "operating_cash_flow to interest",
                    # 'operating-cash-flow-to-debt': "operating_cash_flow to debt",
                    # 'cash-flow-margin-ratio-formula': "Cash Flow Margin Ratio Formula",
                    # 'cash-flow-to-debt': "Cash flow-to-debt",
                    # 'net-cash-flow-to-capital-expenditures': "Net cash flow-to-capital expenditures",
                    # 'cash-flow-to-revenue': "Cash flow to revenue",
                    # 'cash-return-on-assets': "Cash return on assets",
                    # 'cash-return-on-equity': "cash return on equity",
                    # 'cash-to-income-ratio': "Cash to income ratio",
                    # 'cash-flow-per-share': "Cash flow per share",
                    # 'debt-payment': "Debt payment",
                    # 'debt-coverage': "Debt Coverage",
                    # 'cash-flow-from-operations-ratio': "Cash flow from operations ratio",
                    # 'gross-profit-margin': "Gross profit margin",
                    # 'rece​ivables-turnover': "Rece​ivables Turnover",
                    # 'capital-turnover-ratio': "Capital Turnover Ratio",
                    # 'assets-turnover-ratio': "Assets Turnover Ratio",
                    # 'accounts-receivableturnover': "accounts_receivableturnover",
                    # 'operating-cash-flow-to-debt': "operating_cash_flow to debt",
                    # 'inventory-ratio': "Inventory Ratio",
                    # 'return-on-investment': "Return on investment",

                    # 'pretax-margin': "Pretax Margin",
                    # 'income-to-net-worth-ratio': "Income to Net Worth Ratio",
                    # 'return-on-assets-roa': "Return on Assets (ROA)",
                    # 'roe': "ROE",
                    # 'profit-margin': "Profit Margin",
                    # 'earnings-per-share': "Earnings Per Share ",
                    # 'current-cash-debt-coverage': "Current cash debt coverage",
                    # 'cash-debt-coverage': "Cash debt coverage",
                    # 'long-term-debt-ratio': "Long-Term Debt Ratio ",
                    # 'long-term-debt-equity-ratio': "Long Term Debt/Equity Ratio",
                    # 'lt-debt-as-pct-of-total-debt': "LT-Debt as % of Total Debt",
                    # 'inventory-pct-of-revenue': "Inventory % of Revenue",
                    # 'intangibles-pct-of-book-value': "Intangibles % of Book Value",
                    # 'ffo-funds-from-operations-to-debt': "FFO (Funds from operations) to debt",
                    # 'operating-margin': "Operating Margin",
                    # 'cash-coverage-ratio': "Cash coverage ratio",
                    # 'ebitda-per-share': "EBITDA per share",
                    # 'ebitda-interest-coverage': "ebitda interest coverage",
                    # 'ebitda-margin': "EBITDA Margin",
                    # 'net-margin-profit-margin': "Net Margin (Profit Margin)",
                    # 'return-on-capital-employed-ratio': "Return on Capital Employed Ratio",
                    # 'debt-service-ratio': "Debt Service Ratio",
                    # 'return-on-capital': "Return on capital",
                    # 'dividend-yield': "Dividend Yield",
                    # 'dividend-payout-ratio': "Dividend Payout Ratio",
                    # 'dividends-per-share': "Dividends per share",
                    # 'inventory-turnover': "inventory turnover",
                    # 'cash-ratio': "Cash Ratio",
                    # 'cash-flow-roa': "Cash Flow ROA",
                    # 'average-collection-period': "Average Collection Period",
                    # 'number-of-days-of-receivables': "Number of days of receivables",
                    # 'average-days-payables-outstanding': "Average days payables outstanding",
                    # 'days-sales-in-payables': "Days sales in payables",
                    # }

# https://stackoverflow.com/questions/16756174/python-one-line-function-definition

# def metric_to_list_variables_map(df,metric):

def metric_to_formula_map(df,metric):
	metric_to_formula_map = {
        # 'roa_cash_flow':df['operating_cash_flow']/df['total_assets'],
	    'net_working_capital_ratio':df['working_capital_math']/df['total_assets'],
	    'book_value_per_share':df['total_se']/df['shares_outstanding_non'],
        'long_term_debt_to_equity_ratio': df['long_term_debt']/df['total_se'],
	    'total_equity_to_total_assets':df['total_se']/df['total_assets'],
	    'operating_cost_ratio':(df['total_opex'] - df['d_n_a'])/df['net_revenue'],
	    'perc​entage_of_debt_to_asset_formula':df['total_non_current_liabilities']/df['total_assets'],


	    'total_liabilities_pct_of_total_assets':df['total_liabilities']/df['total_assets'],
	    'debt_to_assets_ratio':df['total_debt']/df['total_assets'],
	    'debt_to_equity_ratio':df['total_debt']/df['total_se'],
	    'quick_ratio':(df['total_current_assets']-df['inventory'])/df['total_current_liabilities'],
	    'working_capital':df['total_current_assets'] - df['total_current_liabilities'],
	    'current_ratio':df['total_current_assets']/df['total_current_liabilities'],
	    'capital_intensity':df['total_assets']/df['net_revenue'],
	    'equity_multiplier':df['total_assets']/df['total_se'],
	    'short_term_debt_to_equity_ratio':df['short_term_debt']/df['total_se'],
	    'st_debt_as_pct_of_total_debt':df['short_term_debt']/df['total_liabilities'],
	    'acid_test_ratio':df['quick_assets_math']/df['total_current_liabilities'],
	    'pre_tax_income_to_sales':df['pretax_income_non']/df['net_revenue'],
	    'pre_tax_return_on_assets':df['pretax_income_non']/df['total_assets'],
	    'pre_tax_return_on_common_equity':df['pretax_income_non']/df['common_stock'],
	    'operating_roa':df['operating_income']/df['total_assets'],
	    'operating_profit_margin':df['operating_income']/df['net_revenue'],
	    'free_operating_cash_flow_to_debt':(df['operating_cash_flow']-df['capex'])/df['total_debt'],
	    'discretionary_cash_flow_to_debt':df['operating_cash_flow']-df['accounts_payable']-df['debt_repayment']-df['dividends_paid']-df['interest_expense']/df['total_debt'],
	    'operating_cash_flow_to_interest':df['operating_cash_flow'] + df['interest_expense'] + df['income_tax_expense']/df['interest_expense'],
	    'operating_cash_flow_to_debt':df['operating_cash_flow'] + df['interest_expense'] + df['income_tax_expense']/df['total_liabilities'],
	    'cash_flow_margin_ratio_formula':df['operating_cash_flow']/df['total_liabilities'],
	    'cash_flow_to_debt':df['operating_cash_flow']/df['total_debt'],
	    'net_cash_flow_to_capital_expenditures':df['operating_cash_flow']/df['capex'],
	    'cash_flow_to_revenue':df['operating_cash_flow']/df['net_revenue'],
	    'cash_return_on_assets':df['operating_cash_flow']/df['total_assets'],
	    'cash_return_on_equity':df['operating_cash_flow']/df['total_se'],
	    'cash_to_income_ratio':df['operating_cash_flow']/df['operating_income'],
	    'cash_flow_per_share':df['operating_cash_flow']/df['shares_outstanding_non'],
	    'debt_payment':df['operating_cash_flow']/df['debt_repayment'],
	    'debt_coverage':df['operating_cash_flow']/df['long_term_debt'],
	    'cash_flow_from_operations_ratio':df['operating_cash_flow']/df['total_current_liabilities'],
	    'gross_profit_margin':(df['net_revenue'] - df['cost_of_sales'])/df['net_revenue'],
	    # 'receivables_turnover':df['net_revenue']/df['accounts_receivable'],
	    'capital_turnover_ratio':df['net_revenue']/df['working_capital_math'],
	    'assets_turnover_ratio':df['net_revenue']/df['total_assets'],
	    'accounts_receivable_turnover_ratio':df['net_revenue']/df['accounts_receivable'],
	    'operating_cash_flow_to_debt':df['net_revenue']/df['total_se'],
	    'inventory_ratio':df['net_revenue']/df['inventory'],
	    'return_on_investment':df['net_income']+ df['interest_expense']/df['total_se'] + df['long_term_debt'],

	    'pretax_margin':df['net_income'] - df['income_tax_expense']/df['net_revenue'],
	    'income_to_net_worth_ratio':(df['net_income'] - df['deferred_income_tax'])/df['shares_outstanding_non'],
	    'return_on_assets_roa':df['net_income']/df['total_assets'],
	    'return_on_equity_roe':df['net_income']/df['total_se'],
	    'net_profit_margin':df['net_income']/df['net_revenue'],
	    'earnings_per_share':df['net_income']/df['shares_outstanding_non'],
	    'current_cash_debt_coverage':df['net_cash_by_operating_activities']/df['total_current_liabilities'],
	    'cash_debt_coverage':df['net_cash_by_operating_activities']/df['total_liabilities'],
	    'long_term_debt_ratio':df['long_term_debt']/df['total_assets'],
	    'long_term_debt_equity_ratio':df['long_term_debt']/df['total_se'],
	    'lt_debt_as_pct_of_total_debt':df['long_term_debt']/df['total_liabilities'],
	    'inventory_pct_of_revenue':df['inventory']/df['net_revenue'],
	    'intangibles_pct_of_book_value':df['goodwill_n_intangible_assets']/df['total_se'],
	    'ffo_funds_from_operations_to_debt':df['ffo_math']/df['total_debt'],
	    'operating_margin':df['ebitda_non']-df['d_n_a']/df['net_revenue'],
	    'cash_coverage_ratio':df['ebitda_non']/df['interest_expense'],
	    'ebitda_per_share':df['ebitda_non']/df['shares_outstanding_non'],
	    'ebitda_interest_coverage':df['ebitda_non']/df['interest_expense'],
	    'ebitda_margin':df['ebitda_non']/df['net_revenue'],
	    'net_margin_profit_margin':df['net_income']/df['net_revenue'],
	    'return_on_capital_employed_ratio':df['ebit_math']/(df['total_assets'] - df['total_current_liabilities']),
	    'debt_service_ratio':df['ebit_math']/df['interest_expense'],
	    'return_on_capital':df['ebit_math']/df['total_assets'],
	    'dividend_yield':df['dividends_paid']/df['shares_outstanding_non'],
	    'dividend_payout_ratio':df['dividends_paid']/df['net_income'],
	    'dividends_per_share':df['dividends_paid']/df['shares_outstanding_non'],
	    'inventory_turnover':df['cost_of_sales']/df['inventory'],
	    'cash_ratio':df['cash_non']/df['total_current_liabilities'],
	    'cash_flow_roa':df['operating_cash_flow']/df['total_assets'],
	    'average_collection_period':df['accounts_receivable']/df['net_revenue'],
	    'number_of_days_of_receivables':df['accounts_receivable']/df['inventory'],
	    'average_days_payables_outstanding':df['accounts_payable']/df['cost_of_sales'],
	    'days_sales_in_payables':df['accounts_payable']/df['total_opex'],
	}

	metric_history = metric_to_formula_map[metric]
	return metric_history


url_to_var_name_map = {
            'net-working-capital-ratio': "net_working_capital_ratio",
            'long-term-debt-to-equity-ratio': "long_term_debt_to_equity_ratio",
            # 'roa-cash-flow': "roa_cash_flow",
            'book-value-per-share': "book_value_per_share",
            'total-equity-to-total-assets': "total_equity_to_total_assets",
            'operating-cost-ratio': "operating_cost_ratio",
            'perc​entage-of-debt-to-asset-formula': "perc​entage_of_debt_to_asset_formula",
            'return-on-equity-roe':"return_on_equity_roe",

            'total-liabilities-pct-of-total-assets': "total_liabilities_pct_of_total_assets",
            'debt-to-assets-ratio': "debt_to_assets_ratio",
            'debt-to-equity-ratio': "debt_to_equity_ratio",
            'quick-ratio': "quick_ratio",
            'working-capital': "working_capital",
            'current-ratio': "current_ratio",
            'capital-intensity': "capital_intensity",
            'equity-multiplier': "equity_multiplier",
            'short-term-debt-to-equity-ratio': "short_term_debt_to_equity_ratio",
            'st-debt-as-pct-of-total-debt': "st_debt_as_pct_of_total_debt",
            'acid-test-ratio': "acid_test_ratio",
            'pre-tax-income-to-sales': "pre_tax_income_to_sales",
            'pre-tax-return-on-assets': "pre_tax_return_on_assets",
            'pre-tax-return-on-common-equity': "pre_tax_return_on_common_equity",
            'operating-roa': "operating_roa",
            'operating-profit-margin': "operating_profit_margin",
            'free-operating-cash-flow-to-debt': "free_operating_cash_flow_to_debt",
            'discretionary-cash-flow-to-debt': "discretionary_cash_flow_to_debt",
            'operating-cash-flow-to-interest': "operating_cash_flow_to_interest",
            'operating-cash-flow-to-debt': "operating_cash_flow_to_debt",
            'cash-flow-margin-ratio-formula': "cash_flow_margin_ratio_formula",
            'cash-flow-to-debt': "cash_flow_to_debt",
            'net-cash-flow-to-capital-expenditures': "net_cash_flow_to_capital_expenditures",
            'cash-flow-to-revenue': "cash_flow_to_revenue",
            'cash-return-on-assets': "cash_return_on_assets",
            'cash-return-on-equity': "cash_return_on_equity",
            'cash-to-income-ratio': "cash_to_income_ratio",
            'cash-flow-per-share': "cash_flow_per_share",
            'debt-payment': "debt_payment",
            'debt-coverage': "debt_coverage",
            'cash-flow-from-operations-ratio': "cash_flow_from_operations_ratio",
            'gross-profit-margin': "gross_profit_margin",
            'rece​ivables-turnover': "rece​ivables_turnover",
            'capital-turnover-ratio': "capital_turnover_ratio",
            # 'assets-turnover-ratio': "assets_turnover_ratio",
            'accounts-receivable-turnover-ratio': "accounts_receivable_turnover_ratio",
            'operating-cash-flow-to-debt': "operating_cash_flow_to_debt",
            'inventory-ratio': "inventory_ratio",
            'return-on-investment': "return_on_investment",

            'pretax-margin': "pretax_margin",
            'income-to-net-worth-ratio': "income_to_net_worth_ratio",
            'return-on-assets-roa': "return_on_assets_roa",
            'return-on-equity-roe': "return_on_equity_roe",
            'net-profit-margin': "net_profit_margin",
            'earnings-per-share': "earnings_per_share",
            'current-cash-debt-coverage': "current_cash_debt_coverage",
            'cash-debt-coverage': "cash_debt_coverage",
            'long-term-debt-ratio': "long_term_debt_ratio",
            'long-term-debt-equity-ratio': "long_term_debt_equity_ratio",
            'lt-debt-as-pct-of-total-debt': "lt_debt_as_pct_of_total_debt",
            'inventory-pct-of-revenue': "inventory_pct_of_revenue",
            'intangibles-pct-of-book-value': "intangibles_pct_of_book_value",
            'ffo-funds-from-operations-to-debt': "ffo_funds_from_operations_to_debt",
            'operating-margin': "operating_margin",
            'cash-coverage-ratio': "cash_coverage_ratio",
            'ebitda-per-share': "ebitda_per_share",
            'ebitda-interest-coverage': "ebitda_interest_coverage",
            'ebitda-margin': "ebitda_margin",
            'net-margin-profit-margin': "net_margin_profit_margin",
            'return-on-capital-employed-ratio': "return_on_capital_employed_ratio",
            'debt-service-ratio': "debt_service_ratio",
            'return-on-capital': "return_on_capital",
            'dividend-yield': "dividend_yield",
            'dividend-payout-ratio': "dividend_payout_ratio",
            'dividends-per-share': "dividends_per_share",
            'inventory-turnover': "inventory_turnover",
            'cash-ratio': "cash_ratio",
            'cash-flow-roa': "cash_flow_roa",
            'average-collection-period': "average_collection_period",
            'number-of-days-of-receivables': "number_of_days_of_receivables",
            'average-days-payables-outstanding': "average_days_payables_outstanding",
            'days-sales-in-payables': "days_sales_in_payables",
            }
